### ISSUE TITLE
how to create IndexType.NonUnique  index  in slqserver  ??

### ISSUE THREAD

**Issue by bikaqiou2000** [adamosoftware/SchemaSync#33]
public class Index : DbObject
{
//... ...
		public override IEnumerable<string> CreateCommands(SqlSyntax syntax)
		{
//... ...
			switch (Type)
			{
				case IndexType.UniqueIndex
//... ...
**_//IndexType.NonUnique ?????_**
				case IndexType.UniqueConstraint:
//... ...
				case IndexType.PrimaryKey
//... ...
			}
		}
//... ...
}

**Comment by adamosoftware** [comment]
For now I have chosen not to support non-unique indexes because they are mainly optimizations. I find myself relying on Tuning Advisor to suggest non-unique indexes, because it comes up with stuff I would never think of that I don't feel belongs in C# model classes.
